package metricplugin

import (
	"time"

	bsmsg "github.com/ipfs/go-bitswap/message"
	"github.com/ipfs/go-cid"
	"github.com/libp2p/go-libp2p-core/peer"
	ma "github.com/multiformats/go-multiaddr"
	"github.com/pkg/errors"
)

// A BitswapMessage is the type pushed to remote clients for recorded incoming
// Bitswap messages.
type BitswapMessage struct {
	// Wantlist entries sent with this message.
	WantlistEntries []bsmsg.Entry `json:"wantlist_entries"`

	// Whether the wantlist entries are a full new wantlist.
	FullWantList bool `json:"full_wantlist"`

	// Blocks sent with this message.
	Blocks []cid.Cid `json:"blocks"`

	// Block presence indicators sent with this message.
	BlockPresences []BlockPresence `json:"block_presences"`

	// Underlay addresses of the peer we were connected to when the message
	// was received.
	ConnectedAddresses []ma.Multiaddr `json:"connected_addresses"`
}

// A BlockPresence indicates the presence or absence of a block.
type BlockPresence struct {
	// Cid is the referenced CID.
	Cid cid.Cid `json:"cid"`

	// Type indicates the block presence type.
	Type BlockPresenceType `json:"block_presence_type"`
}

// BlockPresenceType is an enum for presence or absence notifications.
type BlockPresenceType int

// Block presence constants.
const (
	// Have indicates that the peer has the block.
	Have BlockPresenceType = 0
	// DontHave indicates that the peer does not have the block.
	DontHave BlockPresenceType = 1
)

// ConnectionEventType specifies the type of connection event.
type ConnectionEventType int

const (
	// Connected specifies that a connection was opened.
	Connected ConnectionEventType = 0
	// Disconnected specifies that a connection was closed.
	Disconnected ConnectionEventType = 1
)

// A ConnectionEvent is the type pushed to remote clients for recorded
// connection events.
type ConnectionEvent struct {
	// The multiaddress of the remote peer.
	Remote ma.Multiaddr `json:"remote"`

	// The type of this event.
	ConnectionEventType ConnectionEventType `json:"connection_event_type"`
}

// An EventSubscriber can handle events generated by the monitor.
type EventSubscriber interface {
	// ID should return a unique identifier.
	// The identifier is used to keep track of subscribers.
	// The identifier may be reused, but only after the old use has been
	// unsubscribed.
	ID() string

	// BitswapMessageReceived handles a Bitswap message that was recorded by the
	// monitor.
	// This must not block.
	BitswapMessageReceived(timestamp time.Time, peer peer.ID, msg BitswapMessage) error

	// ConnectionEventRecorded handles a connection event that was recorded by
	// the monitor.
	// This must not block.
	ConnectionEventRecorded(timestamp time.Time, peer peer.ID, connEvent ConnectionEvent) error
}

// ErrAlreadySubscribed is returned by Subscribe if the given EventSubscriber is
// already subscribed.
var ErrAlreadySubscribed = errors.New("already subscribed")

// The MonitoringAPI encompasses methods related to monitoring Bitswap traffic.
// These are served via the TCP pubsub mechanism.
type MonitoringAPI interface {
	// Subscribe adds a subscriber to the event subscription service.
	// Returns ErrAlreadySubscribed if the given subscriber is already subscribed.
	// An EventSubscriber that returns an error on one of the notification
	// methods will be removed from the list of subscribers.
	Subscribe(subscriber EventSubscriber) error

	// Unsubscribe removes a subscriber from the event subscription service.
	// It is safe to call this multiple times with the same subscriber.
	Unsubscribe(subscriber EventSubscriber)
}

// The RPCAPI is the interface for RPC-like method calls.
// These are served via HTTP, reliably.
type RPCAPI interface {
	// MonitoringAddresses returns listening addresses to connect to for
	// Bitswap monitoring.
	MonitoringAddresses() []string

	// Ping is a no-op.
	Ping()

}

// PluginAPI describes the functionality provided by this monitor to remote
// clients.
type PluginAPI interface {
	MonitoringAPI

	RPCAPI
}
